#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-islam-s1bitflip"
TEST_SCRIPT="$SCRIPT_DIR/test_dilithium_islam_s1_bitflip.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

FAULT_ENABLE="${FAULT_ENABLE:-0}"
S1_BYTE_OFFSET="${S1_BYTE_OFFSET:-0}"
BIT_MASK="${BIT_MASK:-1}"
RESTORE_AFTER_SIGN="${RESTORE_AFTER_SIGN:-1}"
VERIFY_AFTER_SIGN="${VERIFY_AFTER_SIGN:-0}"

ISLAM_HPC_SIGN_CYCLES_MIN="${ISLAM_HPC_SIGN_CYCLES_MIN:-0}"
ISLAM_HPC_SIGN_CYCLES_MAX="${ISLAM_HPC_SIGN_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-islam-s1bitflip-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS
export FAULT_ENABLE S1_BYTE_OFFSET BIT_MASK RESTORE_AFTER_SIGN VERIFY_AFTER_SIGN
export ISLAM_HPC_SIGN_CYCLES_MIN ISLAM_HPC_SIGN_CYCLES_MAX
export TARGET_NAME HEX_PATH
