#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-kyber51290s-xagawa-fail"
TEST_SCRIPT="$SCRIPT_DIR/test_kyber_xagawa_failure.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

CORRUPT_OFFSET="${CORRUPT_OFFSET:-0}"
CORRUPT_MASK="${CORRUPT_MASK:-1}"

XAGAWA_HPC_TARGET_CMOV_CYCLES_MIN="${XAGAWA_HPC_TARGET_CMOV_CYCLES_MIN:-0}"
XAGAWA_HPC_TARGET_CMOV_CYCLES_MAX="${XAGAWA_HPC_TARGET_CMOV_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-kyber51290s-xagawa-fail-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS CORRUPT_OFFSET CORRUPT_MASK
export XAGAWA_HPC_TARGET_CMOV_CYCLES_MIN XAGAWA_HPC_TARGET_CMOV_CYCLES_MAX
export TARGET_NAME HEX_PATH
