#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-wang-faulty-keccak"
TEST_SCRIPT="$SCRIPT_DIR/test_wang_faulty_keccak.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

MODEL="${MODEL:-}"
STOP_ROUND="${STOP_ROUND:-8}"
SKIP_ROUND="${SKIP_ROUND:-7}"
MESSAGE_TWEAK="${MESSAGE_TWEAK:-0}"

WANG_HPC_TARGET_CYCLES_MIN="${WANG_HPC_TARGET_CYCLES_MIN:-0}"
WANG_HPC_TARGET_CYCLES_MAX="${WANG_HPC_TARGET_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-wang-faulty-keccak-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS
export MODEL STOP_ROUND SKIP_ROUND MESSAGE_TWEAK
export WANG_HPC_TARGET_CYCLES_MIN WANG_HPC_TARGET_CYCLES_MAX
export TARGET_NAME HEX_PATH
