#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-wang-onepiece"
TEST_SCRIPT="$SCRIPT_DIR/test_wang_onepiece_decoder.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

MODEL="${MODEL:-}"
TARGET_WORD="${TARGET_WORD:-17}"
TARGET_BIT="${TARGET_BIT:-5}"
PREVIOUS_BIT="${PREVIOUS_BIT:-0}"
MESSAGE_TWEAK="${MESSAGE_TWEAK:-0}"

ONEPIECE_HPC_TARGET_CYCLES_MIN="${ONEPIECE_HPC_TARGET_CYCLES_MIN:-0}"
ONEPIECE_HPC_TARGET_CYCLES_MAX="${ONEPIECE_HPC_TARGET_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-wang-onepiece-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS
export MODEL TARGET_WORD TARGET_BIT PREVIOUS_BIT MESSAGE_TWEAK
export ONEPIECE_HPC_TARGET_CYCLES_MIN ONEPIECE_HPC_TARGET_CYCLES_MAX
export TARGET_NAME HEX_PATH
