#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../common.sh"
source "$SCRIPT_DIR/exp_env.sh"

PLATFORM_NAME="${PLATFORM:-$DEFAULT_PLATFORM}"
SS_VERSION="${SS_VER:-$DEFAULT_SS_VER}"
CRYPTO_TARGET_NAME="${CRYPTO_TARGET:-$DEFAULT_CRYPTO_TARGET}"

OUT_HEX="${FW_TARGET_NAME}-${PLATFORM_NAME}.hex"

cd "$FW_APP_DIR"

make clean CRYPTO_TARGET="$CRYPTO_TARGET_NAME"

make PLATFORM="$PLATFORM_NAME" \
     SS_VER="$SS_VERSION" \
     CRYPTO_TARGET="$CRYPTO_TARGET_NAME" \
     EXTRA_CFLAGS="-DATTACK_DECODER_SKIP_QHALF=0" \
     "$OUT_HEX"

ls -lh "$OUT_HEX"
