#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-fiddling-twiddle"
TEST_SCRIPT="$SCRIPT_DIR/test_fiddling_twiddle.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

# Models: none, ptr, value
MODEL="${MODEL:-none}"
TARGET_J="${TARGET_J:-17}"
TWIDDLE_INDEX="${TWIDDLE_INDEX:-29}"
WRONG_INDEX="${WRONG_INDEX:-0}"
FAULT_VALUE="${FAULT_VALUE:-0}"

FIDDLING_HPC_TARGET_CYCLES_MIN="${FIDDLING_HPC_TARGET_CYCLES_MIN:-0}"
FIDDLING_HPC_TARGET_CYCLES_MAX="${FIDDLING_HPC_TARGET_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-fiddling-twiddle-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS
export MODEL TARGET_J TWIDDLE_INDEX WRONG_INDEX FAULT_VALUE
export FIDDLING_HPC_TARGET_CYCLES_MIN FIDDLING_HPC_TARGET_CYCLES_MAX
export TARGET_NAME HEX_PATH
