#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-kundu-carry"
TEST_SCRIPT="$SCRIPT_DIR/test_kundu_carry_fault.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

MODEL="${MODEL:-}"
TARGET_COEFF="${TARGET_COEFF:-17}"
TARGET_BIT="${TARGET_BIT:-7}"
MESSAGE_TWEAK="${MESSAGE_TWEAK:-0}"

KUNDU_HPC_TARGET_CYCLES_MIN="${KUNDU_HPC_TARGET_CYCLES_MIN:-0}"
KUNDU_HPC_TARGET_CYCLES_MAX="${KUNDU_HPC_TARGET_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-kundu-carry-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS
export MODEL TARGET_COEFF TARGET_BIT MESSAGE_TWEAK
export KUNDU_HPC_TARGET_CYCLES_MIN KUNDU_HPC_TARGET_CYCLES_MAX
export TARGET_NAME HEX_PATH
