#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-nnuo"
TEST_SCRIPT="$SCRIPT_DIR/test_dilithium_nonce_fault.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

# Dilithium2 has L=4, K=4. The first s2 sampling call is call L = 4.
TARGET_CALL="${TARGET_CALL:-4}"

# Default stale nonce models the second sampling group receiving stale base nonce 0.
STALE_NONCE="${STALE_NONCE:-0}"

NNUO_HPC_TARGET_SAMPLE_CYCLES_MIN="${NNUO_HPC_TARGET_SAMPLE_CYCLES_MIN:-0}"
NNUO_HPC_TARGET_SAMPLE_CYCLES_MAX="${NNUO_HPC_TARGET_SAMPLE_CYCLES_MAX:-0}"
NNUO_CHECK_NONCE_PROGRESS="${NNUO_CHECK_NONCE_PROGRESS:-1}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-nnuo-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

MESSAGE_HEX="${MESSAGE_HEX:-4e756d626572204e6f742055736564204f6e6365}"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS TARGET_CALL STALE_NONCE
export NNUO_HPC_TARGET_SAMPLE_CYCLES_MIN NNUO_HPC_TARGET_SAMPLE_CYCLES_MAX NNUO_CHECK_NONCE_PROGRESS
export TARGET_NAME HEX_PATH MESSAGE_HEX
