#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-kyber51290s-roulette"
TEST_SCRIPT="$SCRIPT_DIR/test_kyber_roulette.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

# Models: none, skip, const, random, bitflip
MODEL="${MODEL:-none}"
TARGET_COEFF="${TARGET_COEFF:-17}"
CONST_VALUE="${CONST_VALUE:-0}"
BIT_MASK="${BIT_MASK:-1}"
RAND_SEED="${RAND_SEED:-0x12345678}"

ROULETTE_HPC_TARGET_CYCLES_MIN="${ROULETTE_HPC_TARGET_CYCLES_MIN:-0}"
ROULETTE_HPC_TARGET_CYCLES_MAX="${ROULETTE_HPC_TARGET_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-kyber51290s-roulette-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS MODEL TARGET_COEFF CONST_VALUE BIT_MASK RAND_SEED
export ROULETTE_HPC_TARGET_CYCLES_MIN ROULETTE_HPC_TARGET_CYCLES_MAX
export TARGET_NAME HEX_PATH
