#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FW_APP_DIR="$REPO_ROOT/firmware/cw-dilithium-valsaraj-wrongseed"
TEST_SCRIPT="$SCRIPT_DIR/test_valsaraj_wrong_seed.py"

PLATFORM="${PLATFORM:-CWLITEARM}"
SS_VER="${SS_VER:-SS_VER_2_1}"
BAUD="${BAUD:-230400}"
TRIALS="${TRIALS:-1}"

MODEL="${MODEL:-}"
INTENDED_DOMAIN="${INTENDED_DOMAIN:-2}"
WRONG_DOMAIN="${WRONG_DOMAIN:-1}"
MESSAGE_TWEAK="${MESSAGE_TWEAK:-0}"

VALSARAJ_HPC_TARGET_CYCLES_MIN="${VALSARAJ_HPC_TARGET_CYCLES_MIN:-0}"
VALSARAJ_HPC_TARGET_CYCLES_MAX="${VALSARAJ_HPC_TARGET_CYCLES_MAX:-0}"

TARGET_NAME="${TARGET_NAME:-cw-dilithium-valsaraj-wrongseed-singlebin}"
HEX_PATH="$FW_APP_DIR/${TARGET_NAME}-${PLATFORM}.hex"

export SCRIPT_DIR REPO_ROOT FW_APP_DIR TEST_SCRIPT
export PLATFORM SS_VER BAUD TRIALS
export MODEL INTENDED_DOMAIN WRONG_DOMAIN MESSAGE_TWEAK
export VALSARAJ_HPC_TARGET_CYCLES_MIN VALSARAJ_HPC_TARGET_CYCLES_MAX
export TARGET_NAME HEX_PATH
